<?php

namespace App\Controller\Admin;

use Cake\ORM\TableRegistry;
use App\Controller\Admin\AppController;

/**
 * DescriptorState Controller
 *
 * @property \App\Model\Table\DescriptorStateTable $DescriptorState
 *
 * @method \App\Model\Entity\DescriptorState[] paginate($object = null, array $settings = [])
 */
class DescriptorStateBioquimicaController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_padre = "Fenotipica";
        $this->loadModel('Descriptor');
        $this->loadModel('DescriptorState');
        $this->loadModel('Specie');

        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' =>'BioquimicaMicro'])->first();
        if(!empty($this->module))
          $this->permiso=$this->Functions->validarModulo($this->module->id);

    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index( $idx = null, $idy = null )
    {

        if($this->permiso['index']){

                $styles  = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
                $scripts = ['assets/js/select2/select2', 'assets/js/datatable/jquery.dataTables.min',
                            'assets/js/datatable/dataTables.bootstrap.min',
                            'assets/js/datatable/dataTables.select.min'];

                $especie = $this->Specie->find()->where(['Specie.id' => $idx])->first();

                if($especie!=NULL) {

                        $descriptor      = $this->Descriptor->find()->where(['id' => $idy,'status'=>1])->first();
                        $permiso=$this->permiso;

                        if($descriptor!=NULL) {

                            $descriptorState = $this->DescriptorState->find()->contain('Descriptor')->where(['DescriptorState.descriptor_id' => $idy, 'DescriptorState.status !=' => '0'])->order('DescriptorState.code ASC')->all();

                            if($descriptorState!=NULL) {

                                $mod_padre  = $this->mod_padre;
                                $mod_parent = $descriptor['name'];

                                $this->set(compact('descriptorState', 'descriptor', 'styles', 'scripts', 'mod_padre', 'mod_parent','permiso', 'especie'));
                                $this->set('_serialize', ['descriptorState']);

                            }

                        } else {

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index','controller'=>'DescriptorBioquimica',$idx]);

                        }

                } else {

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index','controller'=>'DescriptorBioquimica',$idx]);

                }

        } else {

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'DescriptorBioquimica',$idx]);
        }
    }

    /**
     * View method
     *
     * @param string|null $id Descriptor State id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
         $this->Flash->error(__('Operación denegada.'));
         return $this->redirect(['action' => 'index',$idx,$idy]);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add( $idx = null, $idy = null )
    {

        if($this->permiso['add']) {

                $especie = $this->Specie->find()->where(['Specie.id' => $idx])->first();

                if($especie!=NULL) {

                        $descriptor = $this->Descriptor->find()->where(['id' => $idy,'status' => 1, 'resource_id' => 3,'specie_id'=>$idx])->first();

                        if($descriptor!=NULL) {

                                $descriptorState = $this->DescriptorState->newEntity();

                                $mod_padre  = $this->mod_padre;
                                $mod_parent = $descriptor['name'];

                                if ($this->request->is('post')) {

                                    $data = $this->request->getData();

                                    $data['status'] = '1';
                                    $data['descriptor_id'] = $descriptor['id'];

                                    $descriptorState = $this->DescriptorState->patchEntity($descriptorState, $data);

                                    if ($this->DescriptorState->save($descriptorState)) {

                                        $descriptorTable = TableRegistry::get('Descriptor');
                                        $descriptor_model = $descriptorTable->get($descriptorState->descriptor_id);

                                        if($descriptor_model->value_type == '1'){

                                            $descriptor_model->value_type = '2';
                                            $descriptorTable->save($descriptor_model);
                                        }

                                        $list_module = explode('/', $this->request->params['_matchedRoute']);

                                        $user_id    = $this->Auth->User('id');
                                        $module     = $list_module[(count($list_module)-6)];
                                        $action     = $list_module[(count($list_module)-2)].'/'.$list_module[(count($list_module)-1)];
                                        $station_id = $descriptorState->id;
                                        $recurso_id = '3';

                                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                                        $this->Flash->success(__('Estado de descriptor creado satisfactoriamente.'));

                                        return $this->redirect(['action' => 'index', 'idy' => $descriptor->specie_id, 'idx' => $descriptor->id ]);
                                    }

                                    $this->Flash->error(__('Hubo inconvenientes al crear el estado del Descriptor. Por favor, Otra vez intente.'));
                                }

                                $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

                                $this->set(compact('descriptorState', 'descriptor', 'mod_padre', 'mod_parent', 'scripts'));
                                $this->set('_serialize', ['descriptorState']);

                        } else {

                            $this->Flash->error(__('Operación denegada.'));
                           return $this->redirect(['action' => 'index',$idx,$idy]);

                        }

                } else {

                            $this->Flash->error(__('Operación denegada.'));
                           return $this->redirect(['action' => 'index',$idx,$idy]);

                }


        } else {

            $this->Flash->error(__('Operación denegada.'));
           return $this->redirect(['action' => 'index',$idx,$idy]);

        }
    }

    /**
     * Edit method
     *
     * @param string|null $id Descriptor State id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit( $idx = null, $idy = null, $id = null )
    {

        if ($this->permiso['edit']) {

                $especie = $this->Specie->find()->where(['Specie.id' => $idx])->first();

                if($especie!=NULL) {

                        $descriptor = $this->Descriptor->find()->where(['Descriptor.status '=>'1','id' => $idy,'Descriptor.resource_id'=>3,'Descriptor.specie_id'=>$idx])->first();

                        if($descriptor!=NULL) {

                                $descriptorState = $this->DescriptorState->find()->where(['DescriptorState.status !=' => '0','DescriptorState.id'=>$id,'DescriptorState.descriptor_id'=>$idy])->first();

                                if($descriptorState!=NULL) {

                                        $mod_padre  = $this->mod_padre;
                                        $mod_parent = $descriptor['name'];

                                        if ($this->request->is(['patch', 'post', 'put'])) {

                                            $descriptorState = $this->DescriptorState->patchEntity($descriptorState, $this->request->getData());

                                            if ($this->DescriptorState->save($descriptorState)) {

                                                $list_module = explode('/', $this->request->params['_matchedRoute']);

                                                $user_id    = $this->Auth->User('id');
                                                $module     = $list_module[(count($list_module)-7)];
                                                $action     = $list_module[(count($list_module)-3)].'/'.$list_module[(count($list_module)-2)];
                                                $station_id = $descriptorState->id;
                                                $recurso_id = '3';

                                                $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                                                $this->Flash->success(__('Estado de descriptor actualizado satisfactoriamente.'));

                                                return $this->redirect(['action' => 'index', 'idy' => $descriptor->specie_id, 'idx' => $descriptor->id]);
                                            }

                                            $this->Flash->error(__('Hubo inconvenientes al actualizar el estado del Descriptor. Por favor, Otra vez intente.'));
                                        }

                                        $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

                                        $this->set(compact('descriptorState', 'descriptor', 'mod_padre', 'mod_parent', 'scripts'));
                                        $this->set('_serialize', ['descriptorState']);

                                } else {

                                $this->Flash->error(__('Operación denegada.'));
                                return $this->redirect(['action' => 'index',$idx,$idy]);

                                }

                        } else {

                                $this->Flash->error(__('Operación denegada.'));
                                return $this->redirect(['action' => 'index',$idx,$idy]);

                        }

                } else {

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index',$idx,$idy]);

                }

        } else {

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index',$idx,$idy]);

        }
    }

    /**
     * Delete method
     *
     * @param string|null $id Descriptor State id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($idx = null, $idy = null, $id = null)
    {

        if ($this->permiso['edit']) {

                $especie = $this->Specie->find()->where(['Specie.id' => $idx])->first();

                if($especie!=NULL) {

                        $descriptor = $this->Descriptor->find()->where(['Descriptor.status '=>'1','id' => $idy,'Descriptor.resource_id'=>3,'Descriptor.specie_id'=>$idx])->first();

                        if($descriptor!=NULL) {

                                 $descriptorState = $this->DescriptorState->find()->where(['DescriptorState.status !=' => '0','DescriptorState.id'=>$id,'DescriptorState.descriptor_id'=>$idy])->first();

                                if($descriptorState!=NULL) {

                                        $this->request->is(['post', 'delete']);

                                        $descriptorState = $this->DescriptorState->get($id);
                                        $descriptorState['status'] = '0';

                                        $descriptor = $this->Descriptor->find()->where(['id' => $idy])->first();

                                        if ($this->DescriptorState->save($descriptorState)) {

                                            $list_module = explode('/', $this->request->params['_matchedRoute']);

                                            $user_id    = $this->Auth->User('id');
                                            $module     = $list_module[(count($list_module)-7)];
                                            $action     = $list_module[(count($list_module)-3)].'/'.$list_module[(count($list_module)-2)];
                                            $station_id = $descriptorState->id;
                                            $recurso_id = '3';

                                            $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                                            $this->Flash->success(__('Estado del descriptor eliminado satisfactoriamente.'));

                                        } else {

                                            $this->Flash->error(__('Hubo inconvenientes al eliminar el estado del Descriptor. Por favor, Otra vez intente.'));
                                        }

                                        return $this->redirect(['action' => 'index', 'idy' => $descriptor->specie_id, 'idx' => $descriptor->id]);

                                } else {

                                $this->Flash->error(__('Operación denegada.'));
                                return $this->redirect(['action' => 'index',$idx,$idy]);

                                }

                        } else {

                                $this->Flash->error(__('Operación denegada.'));
                                return $this->redirect(['action' => 'index',$idx,$idy]);

                        }

                } else {

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index',$idx,$idy]);

                }


        } else {

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index',$idx,$idy]);

        }
    }

    public function exportartabla($idx = null, $idy = null) {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT .'reportes/'.$data['filename'].'.xlsx';

            if(file_exists($filePath)){

                $this->response->file($filePath , array('download'=> true));

                return $this->response;

            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }


}
