<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AppController;

/**
 * InsituThreat Controller
 *
 * @property \App\Model\Table\InsituThreatTable $InsituThreat
 *
 * @method \App\Model\Entity\InsituThreat[] paginate($object = null, array $settings = [])
 */
class InsituThreatController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_modulo = "Conservación In Situ";
        $this->mod_title = "Amenazas Reportadas";
        $this->loadModel('Insitu');
        $this->loadModel('Ubigeo');
        $this->loadModel('OptionList');

        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'Insitu'])->first();
        if(!empty($this->module))
          $this->permiso=$this->Functions->validarModulo($this->module->id);
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index( $idx = null )
    {
        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx,'Insitu.status'=>1])->first();

        if ($insitu!=NULL && $this->permiso['index']) {

            $mod_modulo  = $this->mod_modulo;
            $mod_title   = $this->mod_title;
            $permiso     = $this->permiso;

            $styles  = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
            $scripts = ['assets/js/select2/select2', 'assets/js/datatable/jquery.dataTables.min',
                        'assets/js/datatable/dataTables.bootstrap.min',
                        'assets/js/datatable/dataTables.select.min'];

            $insituThreat = $this->InsituThreat->find()->where(['insitu_id' => $insitu->id, 'status' => '1'])->all();

            if ($insituThreat!=NULL) {


                $this->set(compact('insituThreat', 'mod_modulo', 'mod_title', 'styles', 'scripts', 'insitu','permiso'));
                $this->set('_serialize', ['insituThreat']);

            } else {

            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'Insitu']);

            }

        } else {
            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'Insitu']);

        }
    }

    /**
     * View method
     *
     * @param string|null $id Insitu Threat id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($idx = null, $id = null)
    {
        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx,'Insitu.status'=>1])->first();


        if ($insitu!=NULL && $this->permiso['view']) {

            $insituThreat = $this->InsituThreat->find()->contain(['Insitu'])->where(['InsituThreat.id'=> $id,'InsituThreat.insitu_id'=>$idx,'InsituThreat.status'=>1])->first();

            if ($insituThreat!=NULL) {

                $mod_modulo  = $this->mod_modulo;
                $mod_title   = $this->mod_title;
                $permiso     = $this->permiso;

                $this->set(compact('insituThreat', 'mod_modulo', 'mod_title','permiso', 'insitu'));
                $this->set('_serialize', ['insituThreat']);

            } else {

            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituThreat',$idx]);

            }

        } else {

            //$this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituThreat',$idx]);

        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($idx = null)
    {
        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx, 'Insitu.status'=>1])->first();

        if ($insitu!=NULL && $this->permiso['add']) {

            $insituThreat = $this->InsituThreat->newEntity();

            if ($this->request->is('post')) {

                $data = $this->request->getData();

                $data['status'] = '1';
                $data['insitu_id'] = $insitu->id;

                $insituThreat = $this->InsituThreat->patchEntity($insituThreat, $data);

                if ($this->InsituThreat->save($insituThreat)) {

                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                    $user_id    = $this->Auth->User('id');
                    $module     = $list_module[(count($list_module)-2)];
                    $action     = $list_module[(count($list_module)-1)];
                    $station_id = $insituThreat->id;
                    $recurso_id = '4';

                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                    $this->Flash->success(__('Amenaza Reportada creado satisfactoriamente.'));

                    return $this->redirect(['action' => 'index', 'idx' => $insitu->id]);
                }

                $this->Flash->error(__('Hubo inconvenientes al crear la Amenaza Reportada. Por favor, otra vez intente.'));
            }

            $mod_modulo  = $this->mod_modulo;
            $mod_title   = $this->mod_title;

            $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

            $severidad = $this->OptionList->find('list',['keyField'=>'id', 'valueField' => 'name'])->where(['parent_id'=>'653', 'status' => '1', 'resource_id' => 4]);

            $this->set(compact('insituThreat', 'insitu', 'mod_modulo', 'mod_title', 'scripts', 'severidad'));
            $this->set('_serialize', ['insituThreat']);

        } else {

            //$this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituThreat',$idx]);

        }
    }

    /**
     * Edit method
     *
     * @param string|null $id Insitu Threat id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($idx = null, $id = null)
    {
        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx,'Insitu.status'=>1])->first();

        if ($insitu!=NULL && $this->permiso['edit']) {


            $insituThreat = $this->InsituThreat->find()->where(['InsituThreat.id'=>$id,'InsituThreat.status'=>1,'InsituThreat.insitu_id'=>$idx])->first();

            if ($insituThreat!=NULL) {

                if ($this->request->is(['patch', 'post', 'put'])) {

                    $insituThreat = $this->InsituThreat->patchEntity($insituThreat, $this->request->getData());

                    if ($this->InsituThreat->save($insituThreat)) {

                        $list_module = explode('/', $this->request->params['_matchedRoute']);

                        $user_id    = $this->Auth->User('id');
                        $module     = $list_module[(count($list_module)-3)];
                        $action     = $list_module[(count($list_module)-2)];
                        $station_id = $insituThreat->id;
                        $recurso_id = '4';

                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                        $this->Flash->success(__('Amenaza Reportada actualizado satisfactoriamente.'));

                        return $this->redirect(['action' => 'index', 'idx' => $insitu->id]);
                    }

                    $this->Flash->error(__('Hubo inconvenientes al actualizar la Amenaza Reportada. Por favor, otra vez intente.'));
                }

                $mod_modulo = $this->mod_modulo;
                $mod_title  = $this->mod_title;

                $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

                $severidad = $this->OptionList->find('list',['keyField'=>'id', 'valueField' => 'name'])->where(['parent_id'=>'653', 'status' => '1', 'resource_id' => 4]);

                $this->set(compact('insituThreat', 'insitu', 'mod_modulo', 'mod_title', 'scripts', 'severidad'));
                $this->set('_serialize', ['insituThreat']);

            } else {

            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituThreat',$idx]);

            }

        } else {

            //$this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituThreat',$idx]);

        }
    }

    /**
     * Delete method
     *
     * @param string|null $id Insitu Threat id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($idx = null, $id = null)
    {
        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx,'Insitu.status'=>1])->first();

        if ($insitu!=NULL && $this->permiso['delete']) {

            $this->request->is(['post', 'delete']);

            $insituThreat = $this->InsituThreat->find()->where(['InsituThreat.id'=>$id,'InsituThreat.status'=>1,'InsituThreat.insitu_id'=>$idx])->first();

            if ($insituThreat==NULL) {

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'InsituThreat',$idx]);

            }else{

                $insituThreat['status'] = '0';

                if ($this->InsituThreat->save($insituThreat)) {

                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                    $user_id    = $this->Auth->User('id');
                    $module     = $list_module[(count($list_module)-3)];
                    $action     = $list_module[(count($list_module)-2)];
                    $station_id = $insituThreat->id;
                    $recurso_id = '4';

                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                    $this->Flash->success(__('Amenaza Reportada eliminado satisfactoriamente.'));

                } else {

                    $this->Flash->error(__('Hubo inconvenientes al eliminar la Amenaza Reportada. Por favor, otra vez intente.'));
                }

                return $this->redirect(['action' => 'index', 'idx' => $insituThreat->insitu_id]);
            }

        } else {

            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituThreat',$idx]);

        }
    }

    public function exportartabla($idx = null) {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT .'reportes/'.$data['filename'].'.xlsx';

            if(file_exists($filePath)){

                $this->response->file($filePath , array('download'=> true));

                return $this->response;

            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }

}
