<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AppController;

/**
 * InsituPlage Controller
 *
 * @property \App\Model\Table\InsituPlageTable $InsituPlage
 *
 * @method \App\Model\Entity\InsituPlage[] paginate($object = null, array $settings = [])
 */
class InsituPlageController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_modulo = "Conservación In Situ";
        $this->mod_title = "Plagas / Patógenos";
        $this->loadModel('Insitu');
        $this->loadModel('OptionList');

        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'Insitu'])->first();
        if(!empty($this->module))
          $this->permiso=$this->Functions->validarModulo($this->module->id);
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index( $idx = null )
    {

        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx,'Insitu.status'=>'1'])->first();

        if ($insitu!=NULL && $this->permiso['index']) {

            $mod_modulo  = $this->mod_modulo;
            $mod_title   = $this->mod_title;
            $permiso     = $this->permiso;

            $styles  = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
            $scripts = ['assets/js/select2/select2', 'assets/js/datatable/jquery.dataTables.min',
                        'assets/js/datatable/dataTables.bootstrap.min',
                        'assets/js/datatable/dataTables.select.min'];


            $insituPlage = $this->InsituPlage->find()->where(['insitu_id' => $insitu->id, 'status' => '1'])->all();

            if ($insituPlage!=NULL) {

                $this->set(compact('insituPlage', 'insitu', 'mod_modulo', 'mod_title', 'styles', 'scripts','permiso'));
                $this->set('_serialize', ['insituPlage']);

            } else {

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'Insitu']);
            }

        } else {

            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'Insitu']);

        }
    }

    /**
     * View method
     *
     * @param string|null $id Insitu Plage id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($idx = null, $id = null)
    {
        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx,'Insitu.status'=>'1'])->first();

        if ($insitu!=NULL && $this->permiso['view']) {

            $insituPlage = $this->InsituPlage->find()->contain(['Insitu'])->where(['InsituPlage.id'=> $id,'InsituPlage.insitu_id'=>$idx,'InsituPlage.status'=>'1'])->first();

            if ($insituPlage!=NULL) {

            $mod_modulo  = $this->mod_modulo;
            $mod_title   = $this->mod_title;
            $permiso     = $this->permiso;

            $this->set(compact('insituPlage','mod_modulo', 'mod_title','permiso', 'insitu'));
            $this->set('_serialize', ['insituPlage']);

            }else {

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'InsituPlage',$idx]);
            }

        }else {

            // $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituPlage',$idx]);

        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($idx = null)
    {
        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx, 'Insitu.status'=>'1'])->first();

        if ($insitu!=NULL && $this->permiso['add']) {

            $insituPlage = $this->InsituPlage->newEntity();
            // $insitu = $this->Insitu->get($idx);

            if ($this->request->is('post')) {

                $data = $this->request->getData();

                $data['status'] = '1';
                $data['insitu_id'] = $insitu->id;

                $insituPlage = $this->InsituPlage->patchEntity($insituPlage, $data);

                if ($this->InsituPlage->save($insituPlage)) {

                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                    $user_id    = $this->Auth->User('id');
                    $module     = $list_module[(count($list_module)-2)];
                    $action     = $list_module[(count($list_module)-1)];
                    $station_id = $insituPlage->id;
                    $recurso_id = '4';

                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                    $this->Flash->success(__('Plaga / Patógeno creado satisfactoriamente.'));

                    return $this->redirect(['action' => 'index', 'idx' => $insitu->id]);
                }

                $this->Flash->error(__('Hubo inconvenientes al crear la Plaga / Patógeno. Por favor, otra vez intente.'));
            }

            $mod_modulo  = $this->mod_modulo;
            $mod_title   = $this->mod_title;

            $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

            $severidad = $this->OptionList->find('list',['keyField'=>'id', 'valueField' => 'name'])->where(['parent_id'=>'653', 'status' => '1', 'resource_id' => 4]);

            $this->set(compact('insituPlage', 'insitu', 'mod_modulo', 'mod_title', 'scripts', 'severidad'));
            $this->set('_serialize', ['insituPlage']);

        } else {

            $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituPlage']);

        }
    }

    /**
     * Edit method
     *
     * @param string|null $id Insitu Plage id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($idx = null, $id = null)
    {

        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx,'Insitu.status'=>'1'])->first();

        if ($insitu!=NULL && $this->permiso['edit']) {

            $insituPlage = $this->InsituPlage->find()->where(['InsituPlage.id'=>$id,'InsituPlage.status'=>'1','InsituPlage.insitu_id'=>$idx])->first();

            if ($insituPlage!=NULL) {

                if ($this->request->is(['patch', 'post', 'put'])) {

                    $insituPlage = $this->InsituPlage->patchEntity($insituPlage, $this->request->getData());

                    if ($this->InsituPlage->save($insituPlage)) {

                        $list_module = explode('/', $this->request->params['_matchedRoute']);

                        $user_id    = $this->Auth->User('id');
                        $module     = $list_module[(count($list_module)-3)];
                        $action     = $list_module[(count($list_module)-2)];
                        $station_id = $insituPlage->id;
                        $recurso_id = '4';

                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);


                        $this->Flash->success(__('Plaga / Patógeno actualizado satisfactoriamente.'));

                        return $this->redirect(['action' => 'index', 'idx' => $insitu->id]);
                    }

                    $this->Flash->error(__('Hubo inconvenientes al actualizar la Plaga / Patógeno. Por favor, otra vez intente.'));
                }

                $mod_modulo  = $this->mod_modulo;
                $mod_title   = $this->mod_title;

                $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];

                $severidad = $this->OptionList->find('list',['keyField'=>'id', 'valueField' => 'name'])->where(['parent_id'=>'653', 'status' => '1', 'resource_id' => 4]);

                $this->set(compact('insituPlage', 'insitu', 'mod_modulo', 'mod_title', 'scripts', 'severidad'));
                $this->set('_serialize', ['insituPlage']);

            }else {

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'InsituPlage',$idx]);

            }

        }else {

            // $this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituPlage',$idx]);

        }

    }

    /**
     * Delete method
     *
     * @param string|null $id Insitu Plage id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($idx = null, $id = null)
    {
        $insitu = $this->Insitu->find()->where(['Insitu.id'=>$idx,'Insitu.status'=>'1'])->first();

        if ($insitu!=NULL && $this->permiso['delete']) {

            $this->request->is(['post', 'delete']);

            $insituPlage = $this->InsituPlage->find()->where(['InsituPlage.id'=>$id,'InsituPlage.status'=>'1','InsituPlage.insitu_id'=>$idx])->first();

            if ($insituPlage==NULL) {

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'InsituPlage',$idx]);

            }else{
                $insituPlage['status'] = 0;

                if ($this->InsituPlage->save($insituPlage)) {

                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                    $user_id    = $this->Auth->User('id');
                    $module     = $list_module[(count($list_module)-3)];
                    $action     = $list_module[(count($list_module)-2)];
                    $station_id = $insituPlage->id;
                    $recurso_id = '4';

                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                    $this->Flash->success(__('Plaga / Patógeno eliminado satisfactoriamente.'));

                } else {

                    $this->Flash->error(__('Hubo inconvenientes al eliminar la Plaga / Patógeno. Por favor, otra vez intente.'));
                }

                return $this->redirect(['action' => 'index', 'idx' => $insituPlage->insitu_id ]);
            }

        }else {

            //$this->Flash->error(__('Operación denegada.'));
            return $this->redirect(['action' => 'index','controller'=>'InsituPlage',$idx]);

        }
    }

    public function exportartabla($idx = null) {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT .'reportes/'.$data['filename'].'.xlsx';

            if(file_exists($filePath)){

                $this->response->file($filePath , array('download'=> true));

                return $this->response;

            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }

}
