<?php

namespace App\Controller\Admin;

use App\Controller\Admin\AppController;

/**
 * LongTermConservationMicro Controller
 *
 * @property \App\Model\Table\LongTermConservationMicroTable $LongTermConservationMicro
 *
 * @method \App\Model\Entity\LongTermConservationMicro[] paginate($object = null, array $settings = [])
 */
class LongTermConservationMicroController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_parent = "Banco Microorganismo ";
        $this->mod_padre = "Conservación a Largo Plazo";
        $this->loadModel('BankMicro');
        $this->loadModel('OptionList');
        $this->loadModel('Passport');

        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'BankMicro'])->first();
        if(!empty($this->module))
          $this->permiso=$this->Functions->validarModulo($this->module->id);
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index($id=null)
    {
        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();


        if($bankMicro_count !=NULL && $this->permiso['index']){

            $styles  = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
            $scripts = ['assets/js/select2/select2', 'assets/js/datatable/jquery.dataTables.min',
                        'assets/js/datatable/dataTables.bootstrap.min',
                        'assets/js/datatable/dataTables.select.min'];

            $longTermConservationMicro = $this->LongTermConservationMicro->find()->where(['LongTermConservationMicro.status !=' => '0', 'bank_micro_id' => $id]);
            $titulo=$this->mod_parent.' - '. $this->mod_padre;
            $titulo_lista=$this->mod_padre;
            $permiso= $this->permiso;

            $this->set(compact('longTermConservationMicro','styles','scripts','titulo','titulo_lista','id','permiso','passport'));
            $this->set('_serialize', ['longTermConservationMicro']);

        } else{

              $this->Flash->error(__('Operación denegada.'));
              return $this->redirect(['action' => 'index','controller'=>'BankMicro']);
        }
    }

    /**
     * View method
     *
     * @param string|null $id Long Term Conservation Micro id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null,$child=null)
    {

        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count ==NULL || !$this->permiso['view']){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'BankMicro']);

        }else{

            $longTermConservationMicro = $this->LongTermConservationMicro->find()
                                             ->where(['LongTermConservationMicro.status !=' => '0','LongTermConservationMicro.id'=>$child,'LongTermConservationMicro.bank_micro_id'=>$id
                                                ])->first();

            if($longTermConservationMicro==NULL){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index',$id]);
            }

            $titulo = $this->mod_padre;
            $parent = $this->mod_parent;
            $permiso= $this->permiso;

            $this->set(compact('longTermConservationMicro','titulo','permiso','id','child','validar'));
            $this->set('_serialize', ['longTermConservationMicro']);
        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($id=null)
    {
        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->count();

        if($bankMicro_count>0 && $this->permiso['add']){


        $longTermConservationMicro = $this->LongTermConservationMicro->newEntity();
        $modulo= $this->mod_padre ;
        $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];
        $longTermConservationMicro->bank_micro_id=$id;

        if ($this->request->is('post')) {

            $data=$this->request->getData();
            $data['status']=1;

            try{
                    $data['bank_micro_id']= $id;
                    $data['constime'] = ($data['fecha_conservacion'] == '' || $data['fecha_conservacion'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_conservacion']));
                    $data['renewal_date'] = ($data['fecha_renovacion'] == '' || $data['fecha_renovacion'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_renovacion']));

                    $longTermConservationMicro = $this->LongTermConservationMicro->patchEntity($longTermConservationMicro,$data);

                    if ($this->LongTermConservationMicro->save($longTermConservationMicro)) {


                            $list_module = explode('/', $this->request->params['_matchedRoute']);

                            $user_id    = $this->Auth->User('id');
                            $module     = $list_module[(count($list_module)-4)];
                            $action     = $list_module[(count($list_module)-2)].'/'.$list_module[(count($list_module)-1)];
                            $station_id = $longTermConservationMicro->id;
                            $recurso_id = '3';

                            $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                            $this->Flash->success(__('La Conservación a Largo Plazo fue creado satisfactoriamente.'));

                            return $this->redirect(['action' => 'index',$longTermConservationMicro->bank_micro_id]);
                    }
                    $this->Flash->error(__('Hubo inconvenientes al crear la Conservación a Largo Plazo. Por favor, Otra vez intente.'));

             } catch (\Exception $e) {

                    $this->Flash->error(__('Hubo inconvenientes al crear la Conservación a Largo Plazo. Por favor, Otra vez intente.'));

                   return $this->redirect(['action' => 'index',$longTermConservationMicro->bank_micro_id]);
            }
        }

        $lista_medio_conservacion= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 528, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $lista_crioprotector= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 540, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $lista_conservacion= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 564, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $lista_lugar_almacenamiento= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 558, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $this->set(compact('scripts','longTermConservationMicro','modulo','id','lista_medio_conservacion','lista_crioprotector','lista_conservacion','lista_lugar_almacenamiento'));
        $this->set('_serialize', ['longTermConservationMicro']);

        }else {

                 $this->Flash->error(__('Operación denegada.'));
                 return $this->redirect(['action' => 'index','controller'=>'BankMicro']);
        }
    }

    /**
     * Edit method
     *
     * @param string|null $id Long Term Conservation Micro id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null,$child=null)
    {
        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count!=NULL /*&& $validar*/){

            $longTermConservationMicro = $this->LongTermConservationMicro->find()
                                         ->where(['LongTermConservationMicro.status !=' => '0','LongTermConservationMicro.id'=>$child,'LongTermConservationMicro.bank_micro_id'=>$id
                                            ])->first();

            if($longTermConservationMicro==NULL){

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index',$id]);
            } else {

                $modulo=$this->mod_padre ;
                $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];
                if ($this->request->is(['patch', 'post', 'put'])) {
                    $data=$this->request->getData();
                    $data['constime'] = ($data['fecha_conservacion'] == '' || $data['fecha_conservacion'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_conservacion']));
                    $data['renewal_date'] = ($data['fecha_renovacion'] == '' || $data['fecha_renovacion'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_renovacion']));
                     try{
                            $longTermConservationMicro = $this->LongTermConservationMicro->patchEntity($longTermConservationMicro,$data);

                            if ($this->LongTermConservationMicro->save($longTermConservationMicro)) {

                                $list_module = explode('/', $this->request->params['_matchedRoute']);

                                $user_id    = $this->Auth->User('id');
                                $module     = $list_module[(count($list_module)-5)];
                                $action     = $list_module[(count($list_module)-3)].'/'.$list_module[(count($list_module)-2)];
                                $station_id = $longTermConservationMicro->id;
                                $recurso_id = '3';

                                $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                                $this->Flash->success(__('La Conservación a Largo Plazo fue actualizada satisfactoriamente.'));

                                return $this->redirect(['action' => 'index',$longTermConservationMicro->bank_micro_id]);
                            }
                            $this->Flash->error(__('Hubo inconvenientes al actualizar la Conservación a Largo Plazo. Por favor, Otra vez intente.'));

                        } catch (\Exception $e) {

                            $this->Flash->error(__('Hubo inconvenientes al actualizar la Conservación a Largo Plazo. Por favor, Otra vez intente.'));
                            return $this->redirect(['action' => 'index']);
                    }
                }
            }

        $lista_medio_conservacion= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 528, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $lista_crioprotector= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 540, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $lista_conservacion= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 564, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $lista_lugar_almacenamiento= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 558, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $longTermConservationMicro->constime=($longTermConservationMicro->constime == NULL) ? NULL : date('d-m-Y', strtotime($longTermConservationMicro->constime));
        $longTermConservationMicro->renewal_date=($longTermConservationMicro->renewal_date == NULL) ? NULL : date('d-m-Y', strtotime($longTermConservationMicro->renewal_date));

        $this->set(compact('scripts','longTermConservationMicro','modulo','lista_medio_conservacion','id','lista_crioprotector','lista_conservacion','lista_lugar_almacenamiento','child'));
        $this->set('_serialize', ['longTermConservationMicro']);

        } else {
                 $this->Flash->error(__('Operación denegada.'));
                 return $this->redirect(['action' => 'index','controller'=>'BankMicro']);
        }
    }

    /**
     * Delete method
     *
     * @param string|null $id Long Term Conservation Micro id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null,$child=null)
    {


        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count!=NULL /*&& $validar*/){

            $this->request->is(['post', 'delete']);

            $longTermConservationMicro = $this->LongTermConservationMicro->find()
                                         ->where(['LongTermConservationMicro.status !=' => '0','LongTermConservationMicro.id'=>$child,'LongTermConservationMicro.bank_micro_id'=>$id
                                            ])->first();

            if($longTermConservationMicro==NULL){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index',$id]);
            }else{

                $longTermConservationMicro['status'] = 0;

                if ($this->LongTermConservationMicro->save($longTermConservationMicro)) {

                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                    $user_id    = $this->Auth->User('id');
                    $module     = $list_module[(count($list_module)-5)];
                    $action     = $list_module[(count($list_module)-3)].'/'.$list_module[(count($list_module)-2)];
                    $station_id = $longTermConservationMicro->id;
                    $recurso_id = '3';

                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);


                    $this->Flash->success(__('La Conservación a Largo Plazo del Material fue eliminado satisfactoriamente.'));
                } else {
                     $this->Flash->error(__('Hubo inconvenientes al eliminar la Conservación a Largo Plazo del Material . Por favor, Otra vez intente.'));
                }

               return $this->redirect(['action' => 'index', $longTermConservationMicro->bank_micro_id]);
            }

        }else{

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'BankMicro']);

        }
    }

    public function exportartabla($id = null) {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT .'reportes/'.$data['filename'].'.xlsx';

            if(file_exists($filePath)){

                $this->response->file($filePath , array('download'=> true));

                return $this->response;

            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }


}
