<?php

namespace App\Controller\Admin;

use App\Controller\Admin\AppController;
/**
 * OutputMicro Controller
 *
 * @property \App\Model\Table\OutputMicroTable $OutputMicro
 *
 * @method \App\Model\Entity\OutputMicro[] paginate($object = null, array $settings = [])
 */
class OutputMicroController extends AppController
{


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_parent = "Banco Microorganismo ";
        $this->mod_padre = "Salida de Material";
        $this->loadModel('BankMicro');
        $this->loadModel('OptionList');
        $this->loadModel('Passport');
        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'BankMicro'])->first();
        if(!empty($this->module))
          $this->permiso=$this->Functions->validarModulo($this->module->id);
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index($id=null)
    {
        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();

        if($bankMicro_count !=NULL && $this->permiso['index']){

                $styles  = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
                $scripts = ['assets/js/select2/select2', 'assets/js/datatable/jquery.dataTables.min',
                            'assets/js/datatable/dataTables.bootstrap.min',
                            'assets/js/datatable/dataTables.select.min'];

                $outputMicro = $this->OutputMicro->find()->where(['OutputMicro.status !=' => '0', 'bank_micro_id' => $id]);
                $titulo=$this->mod_parent.' - '. $this->mod_padre;
                $titulo_lista=$this->mod_padre;
                $permiso= $this->permiso;

                $this->set(compact('outputMicro','styles','scripts','titulo','titulo_lista','id','permiso','passport'));
                $this->set('_serialize', ['outputMicro']);

        } else{

              $this->Flash->error(__('Operación denegada.'));
              return $this->redirect(['action' => 'index','controller'=>'BankMicro']);
        }
    }

    /**
     * View method
     *
     * @param string|null $id Output Micro id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null,$child=null)
    {
        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count ==NULL || !$this->permiso['view']){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'BankMicro']);

        }else{

            $outputMicro = $this->OutputMicro->find()
                                             ->where(['outputMicro.status !=' => '0','outputMicro.id'=>$child,'outputMicro.bank_micro_id'=>$id
                                                ])->first();

            if($outputMicro==NULL){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index',$id]);
            }

            $titulo = $this->mod_padre;
            $parent = $this->mod_parent;
            $permiso= $this->permiso;

            $this->set(compact('outputMicro','titulo','permiso','id','child','validar'));
            $this->set('_serialize', ['outputMicro']);
        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($id=null)
    {

        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->count();

        if($bankMicro_count>0 && $this->permiso['add']){

        $outputMicro = $this->OutputMicro->newEntity();
        $modulo= $this->mod_padre ;
        $outputMicro->bank_micro_id=$id;
        $scripts = ['assets/js/fileinput/fileinput.min','assets/packages/jqueryvalidation/dist/jquery.validate'];

        if ($this->request->is('post')) {
            $data=$this->request->getData();
            $data['status']=1;
            try{
                    $data['bank_micro_id']= $id;
                    $data['exitdate'] = ($data['fecha_salida'] == '' || $data['fecha_salida'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_salida']));

                    $outputMicro = $this->OutputMicro->patchEntity($outputMicro,$data);

                    if ($this->OutputMicro->save($outputMicro)) {

                        $list_module = explode('/', $this->request->params['_matchedRoute']);

                        $user_id    = $this->Auth->User('id');
                        $module     = $list_module[(count($list_module)-4)];
                        $action     = $list_module[(count($list_module)-2)].'/'.$list_module[(count($list_module)-1)];
                        $station_id = $outputMicro->id;
                        $recurso_id = '3';

                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                        $this->Flash->success(__('La Salida de Material fue creado satisfactoriamente.'));

                        return $this->redirect(['action' => 'index',$outputMicro->bank_micro_id]);
                    }
                    $this->Flash->error(__('Hubo inconvenientes al crear la Salida de Material. Por favor, Otra vez intente.'));

             } catch (\Exception $e) {

                    $this->Flash->error(__('Hubo inconvenientes al crear la Salida de Material. Por favor, Otra vez intente.'));

                   return $this->redirect(['action' => 'index',$outputMicro->bank_micro_id]);
            }
        }

        $lista_estado= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 348, 'status' => 1, 'OR' => [['resource_id' => 4]] ]);

        $this->set(compact('outputMicro','modulo','id','lista_estado','scripts'));
        $this->set('_serialize', ['outputMicro']);

        }else {

                 $this->Flash->error(__('Operación denegada.'));
                 return $this->redirect(['action' => 'index','controller'=>'BankMicro']);
        }

    }

    /**
     * Edit method
     *
     * @param string|null $id Output Micro id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null,$child=null)
    {

        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count!=NULL && $this->permiso['edit'] /*&& $validar*/ ){

            $outputMicro = $this->OutputMicro->find()
                                         ->where(['outputMicro.status !=' => '0','outputMicro.id'=>$child,'outputMicro.bank_micro_id'=>$id
                                            ])->first();

            if($outputMicro==NULL){

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index',$id]);
            } else {

                $modulo=$this->mod_padre ;
                $scripts = ['assets/js/fileinput/fileinput.min','assets/packages/jqueryvalidation/dist/jquery.validate'];

                if ($this->request->is(['patch', 'post', 'put'])) {
                    $data=$this->request->getData();
                    $data['exitdate'] = ($data['fecha_salida'] == '' || $data['fecha_salida'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_salida']));
                     try{
                            $outputMicro = $this->OutputMicro->patchEntity($outputMicro,$data);

                            if ($this->OutputMicro->save($outputMicro)) {

                                $list_module = explode('/', $this->request->params['_matchedRoute']);

                                $user_id    = $this->Auth->User('id');
                                $module     = $list_module[(count($list_module)-4)];
                                $action     = $list_module[(count($list_module)-2)].'/'.$list_module[(count($list_module)-1)];
                                $station_id = $outputMicro->id;
                                $recurso_id = '3';

                                $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                                $this->Flash->success(__('La Salida de Material fue actualizada satisfactoriamente.'));

                                return $this->redirect(['action' => 'index',$outputMicro->bank_micro_id]);
                            }
                            $this->Flash->error(__('Hubo inconvenientes al actualizar la Salida de Material. Por favor, Otra vez intente.'));

                        } catch (\Exception $e) {

                            $this->Flash->error(__('Hubo inconvenientes al actualizar la Salida de Material. Por favor, Otra vez intente.'));
                            return $this->redirect(['action' => 'index']);
                    }
                }
            }

        $outputMicro ->exitdate=($outputMicro->exitdate == NULL) ? NULL : date('d-m-Y', strtotime($outputMicro->exitdate));
        $lista_estado= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 348, 'status' => 1, 'OR' => [['resource_id' => 4]] ]);

        $this->set(compact('outputMicro','modulo','lista_estado','id','scripts','child'));
        $this->set('_serialize', ['outputMicro']);

        } else {
                 $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller' => 'BankMicro']);
        }
    }

    /**
     * Delete method
     *
     * @param string|null $id Output Micro id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null,$child=null)
    {

        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count!=NULL && $this->permiso['delete'] /*&& $validar*/ ){

            $this->request->is(['post', 'delete']);

            $outputMicro = $this->OutputMicro->find()
                                         ->where(['outputMicro.status !=' => '0','outputMicro.id'=>$child,'outputMicro.bank_micro_id'=>$id
                                            ])->first();

            if($outputMicro==NULL){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index',$id]);
            }else{

                $outputMicro['status'] = 0;

                if ($this->OutputMicro->save($outputMicro)) {

                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                    $user_id    = $this->Auth->User('id');
                    $module     = $list_module[(count($list_module)-4)];
                    $action     = $list_module[(count($list_module)-2)].'/'.$list_module[(count($list_module)-1)];
                    $station_id = $outputMicro->id;
                    $recurso_id = '3';

                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                    $this->Flash->success(__('La Salida Material fue eliminado satisfactoriamente.'));
                } else {
                     $this->Flash->error(__('Hubo inconvenientes al eliminar la Entrada Material . Por favor, Otra vez intente.'));
                }

               return $this->redirect(['action' => 'index', $outputMicro->bank_micro_id]);
            }

        }else{

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller' => 'BankMicro']);

        }
    }

    public function exportartabla($id=null) {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT .'reportes/'.$data['filename'].'.xlsx';

            if(file_exists($filePath)){

                $this->response->file($filePath , array('download'=> true));

                return $this->response;

            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }


}
