<?php

namespace App\Controller\Admin;

use App\Controller\Admin\AppController;

/**
 * OutputInvitro Controller
 *
 * @property \App\Model\Table\OutputInvitroTable $OutputInvitro
 */
class OutputInvitroController extends AppController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_parent = "Banco Invitro ";
        $this->mod_padre = "Salida de Material";
        $this->loadModel('BankInvitro');
        $this->loadModel('OptionList');
        $this->loadModel('Passport');
        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'BankInvitro'])->first();
        if(!empty( $this->module ))
          $this->permiso=$this->Functions->validarModulo($this->module->id);

    }
    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index($id = null)
    {

        $bankInvitro_count = $this->BankInvitro->find()->where(['BankInvitro.status '=>'1','BankInvitro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankInvitro_count->passport_id])->first();

        if($bankInvitro_count !=NULL && $this->permiso['index']){

            $styles  = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
            $scripts = ['assets/js/select2/select2', 'assets/js/datatable/jquery.dataTables.min',
                        'assets/js/datatable/dataTables.bootstrap.min',
                        'assets/js/datatable/dataTables.select.min'];

            $outputInvitro = $this->OutputInvitro->find()->where(['OutputInvitro.status !=' => '0', 'bank_invitro_id' => $id]);
            $titulo=$this->mod_parent.' - '. $this->mod_padre;
            $titulo_lista=$this->mod_padre;
            $permiso=$this->permiso;

            $this->set(compact('outputInvitro','styles','scripts','titulo','titulo_lista','id','permiso','passport'));
            $this->set('_serialize', ['outputInvitro']);
        }else{
              $this->Flash->error(__('Operación denegada.'));
              return $this->redirect(['action' => 'index','controller'=>'BankInvitro']);
        }
    }

    /**
     * View method
     *
     * @param string|null $id Output Invitro id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null,$child = null)
    {
        $bankInvitro_count = $this->BankInvitro->find()->where(['BankInvitro.status '=>'1','BankInvitro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankInvitro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankInvitro_count ==NULL || !$this->permiso['view']){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'BankInvitro']);

        }else{

            $outputInvitro = $this->OutputInvitro->find()
                                             ->where(['outputInvitro.status !=' => '0','outputInvitro.id'=>$child,'outputInvitro.bank_invitro_id'=>$id
                                                ])->first();

            if($outputInvitro==NULL){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index',$id]);
            }

            $titulo = $this->mod_padre;
            $parent = $this->mod_parent;
            $permiso=$this->permiso;

            $this->set(compact('outputInvitro','titulo','permiso','id','child','validar'));
            $this->set('_serialize', ['outputInvitro']);
        }
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($id = null)
    {

        $bankInvitro_count = $this->BankInvitro->find()->where(['BankInvitro.status '=>'1','BankInvitro.id'=>$id])->count();

        if($bankInvitro_count>0 && $this->permiso['add']){

            $outputInvitro = $this->OutputInvitro->newEntity();
            $modulo= $this->mod_padre ;
            $scripts = ['assets/js/fileinput/fileinput.min','assets/packages/jqueryvalidation/dist/jquery.validate'];

            $outputInvitro->bank_invitro_id=$id;

            if ($this->request->is('post')) {

                $data=$this->request->getData();
                $data['status']=1;
                try{
                        $data['bank_invitro_id']= $id;
                        $data['exitdate'] = ($data['fecha_salida'] == '' || $data['fecha_salida'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_salida']));

                        $outputInvitro = $this->OutputInvitro->patchEntity($outputInvitro,$data);
                        if ($this->OutputInvitro->save($outputInvitro)) {

                            $list_module = explode('/', $this->request->params['_matchedRoute']);

                            $user_id    = $this->Auth->User('id');
                            $module     = $list_module[(count($list_module)-4)];
                            $action     = $list_module[(count($list_module)-2)].'/'.$list_module[(count($list_module)-1)];
                            $station_id = $outputInvitro->id;
                            $recurso_id = '1';

                            $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);
                            $this->Flash->success(__('La Salida de Material fue creado satisfactoriamente.'));

                            return $this->redirect(['action' => 'index',$outputInvitro->bank_invitro_id]);
                        }
                        $this->Flash->error(__('Hubo inconvenientes al crear la Salida de Material. Por favor, Otra vez intente.'));

                 } catch (\Exception $e) {

                        $this->Flash->error(__('Hubo inconvenientes al crear la Salida de Material. Por favor, Otra vez intente.'));
                         return $this->redirect(['action' => 'index',$outputInvitro->bank_invitro_id]);
                }
            }
            $bankInvitro = $this->BankInvitro->find()->where(['id' => $id])->first();

            $this->set(compact('outputInvitro', 'bankInvitro','modulo','scripts','id'));
            $this->set('_serialize', ['outputInvitro']);

        }else {

                 $this->Flash->error(__('Operación denegada.'));
                 return $this->redirect(['action' => 'index','controller'=>'BankInvitro']);
        }
    }

    /**
     * Edit method
     *
     * @param string|null $id Output Invitro id.
     * @return \Cake\Network\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null, $child = null)
    {
        $bankInvitro_count = $this->BankInvitro->find()->where(['BankInvitro.status '=>'1','BankInvitro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankInvitro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankInvitro_count!=NULL && $this->permiso['edit'] /*&& $validar*/ ){

            $outputInvitro = $this->OutputInvitro->find()
                                         ->where(['outputInvitro.status !=' => '0','outputInvitro.id'=>$child,'outputInvitro.bank_invitro_id'=>$id
                                            ])->first();

            if($outputInvitro==NULL){

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index',$id]);
            } else {

                    $scripts = ['assets/js/fileinput/fileinput.min','assets/packages/jqueryvalidation/dist/jquery.validate'];

                    $modulo=$this->mod_padre ;

                    if ($this->request->is(['patch', 'post', 'put'])) {
                        $data=$this->request->getData();
                        $data['exitdate'] = ($data['fecha_salida'] == '' || $data['fecha_salida'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_salida']));
                         try{
                                $outputInvitro = $this->OutputInvitro->patchEntity($outputInvitro,$data);
                                if ($this->OutputInvitro->save($outputInvitro)) {

                                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                                    $user_id    = $this->Auth->User('id');
                                    $module     = $list_module[(count($list_module)-5)];
                                    $action     = $list_module[(count($list_module)-3)].'/'.$list_module[(count($list_module)-2)];
                                    $station_id = $outputInvitro->id;
                                    $recurso_id = '1';

                                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                                    $this->Flash->success(__('La Salida de Material fue actualizada satisfactoriamente.'));

                                    return $this->redirect(['action' => 'index',$outputInvitro->bank_invitro_id]);
                                }
                                $this->Flash->error(__('Hubo inconvenientes al actualizar la Salida de Material. Por favor, Otra vez intente.'));
                            } catch (\Exception $e) {

                                $this->Flash->error(__('Hubo inconvenientes al actualizar la Salida de Material. Por favor, Otra vez intente.'));
                                 return $this->redirect(['action' => 'index',$outputInvitro->bank_invitro_id]);
                        }
                    }
            }


            $outputInvitro->exitdate=($outputInvitro->exitdate == NULL) ? NULL : date('d-m-Y', strtotime($outputInvitro->exitdate));
            $bankInvitro = $this->BankInvitro->find()->where(['id' => $id])->first();

            $this->set(compact('outputInvitro','bankInvitro','scripts','modulo','id','child'));
            $this->set('_serialize', ['outputInvitro']);

        } else {
                 $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'BankInvitro']);
        }
    }

    /**
     * Delete method
     *
     * @param string|null $id Output Invitro id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null, $child = null)
    {

        $bankInvitro_count = $this->BankInvitro->find()->where(['BankInvitro.status '=>'1','BankInvitro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankInvitro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankInvitro_count!=NULL && $this->permiso['delete'] /*&& $validar*/ ){

            $this->request->is(['post', 'delete']);

            $outputInvitro = $this->OutputInvitro->find()
                                         ->where(['outputInvitro.status !=' => '0','outputInvitro.id'=>$child,'outputInvitro.bank_invitro_id'=>$id
                                            ])->first();

            if($outputInvitro==NULL){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index',$id]);
            }else{

                $outputInvitro['status'] = 0;

                if ($this->OutputInvitro->save($outputInvitro)) {

                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                    $user_id    = $this->Auth->User('id');
                    $module     = $list_module[(count($list_module)-5)];
                    $action     = $list_module[(count($list_module)-3)].'/'.$list_module[(count($list_module)-2)];
                    $station_id = $outputInvitro->id;
                    $recurso_id = '1';

                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                    $this->Flash->success(__('La Salida Material fue eliminado satisfactoriamente.'));
                } else {
                     $this->Flash->error(__('Hubo inconvenientes al eliminar la Salida Material . Por favor, Otra vez intente.'));
                }

               return $this->redirect(['action' => 'index', $outputInvitro->bank_invitro_id]);
            }

        }else{

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'BankInvitro']);

        }
    }

    public function exportartabla($id=null) {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT .'reportes/'.$data['filename'].'.xlsx';

            if(file_exists($filePath)){

                $this->response->file($filePath , array('download'=> true));

                return $this->response;

            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }


}
