<?php

namespace App\Controller\Admin;

use App\Controller\Admin\AppController;
/**
 * ShortTermConservationMicro Controller
 *
 * @property \App\Model\Table\ShortTermConservationMicroTable $ShortTermConservationMicro
 *
 * @method \App\Model\Entity\ShortTermConservationMicro[] paginate($object = null, array $settings = [])
 */
class ShortTermConservationMicroController extends AppController
{


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Csrf');
        $this->mod_parent = "Banco Microorganismo";
        $this->mod_padre = "Conservación a Corto Plazo";
        $this->loadModel('BankMicro');
        $this->loadModel('OptionList');
        $this->loadModel('Passport');

        $this->loadModel('Module');
        $this->module = $this->Module->find()->where(['controller' => 'BankMicro'])->first();
        if(!empty($this->module))
          $this->permiso=$this->Functions->validarModulo($this->module->id);
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index($id=NULL)
    {

        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();

        if($bankMicro_count !=NULL && $this->permiso['index']){

            $styles  = ['assets/css/dataTables.bootstrap', 'assets/css/select.bootstrap.min'];
            $scripts = ['assets/js/select2/select2', 'assets/js/datatable/jquery.dataTables.min',
                        'assets/js/datatable/dataTables.bootstrap.min',
                        'assets/js/datatable/dataTables.select.min'];

            $shortTermConservationMicro = $this->ShortTermConservationMicro->find()->where(['ShortTermConservationMicro.status !=' => '0', 'bank_micro_id' => $id]);
            $titulo=$this->mod_parent.' - '. $this->mod_padre;
            $titulo_lista=$this->mod_padre;
            $permiso= $this->permiso;

            $this->set(compact('shortTermConservationMicro','styles','scripts','titulo','titulo_lista','id','permiso','passport'));
            $this->set('_serialize', ['shortTermConservationMicro']);

        } else{

              $this->Flash->error(__('Operación denegada.'));
              return $this->redirect(['action' => 'index','controller'=>'BankMicro']);
        }
    }

    /**
     * View method
     *
     * @param string|null $id Short Term Conservation Micro id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null,$child=null)
    {
        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count ==NULL || !$this->permiso['view']){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller'=>'BankMicro']);

        }else{

            $shortTermConservationMicro = $this->ShortTermConservationMicro->find()
                                             ->where(['ShortTermConservationMicro.status !=' => '0','ShortTermConservationMicro.id'=>$child,'ShortTermConservationMicro.bank_micro_id'=>$id
                                                ])->first();

            if($shortTermConservationMicro==NULL){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index',$id]);
            }

            $titulo = $this->mod_padre;
            $parent = $this->mod_parent;
            $permiso= $this->permiso;

            $this->set(compact('shortTermConservationMicro','titulo','permiso','id','child','validar'));
            $this->set('_serialize', ['shortTermConservationMicro']);
        }
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add($id=null)
    {
       $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->count();

        if($bankMicro_count>0 && $this->permiso['add']){

       $shortTermConservationMicro = $this->ShortTermConservationMicro->newEntity();
       $modulo= $this->mod_padre ;
       $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];
       $shortTermConservationMicro->bank_micro_id=$id;

        if ($this->request->is('post')) {
            $data=$this->request->getData();
            $data['status']=1;
            try{
                    $data['bank_micro_id']= $id;
                    $data['constime'] = ($data['fecha_conservacion'] == '' || $data['fecha_conservacion'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_conservacion']));
                    $data['renewal_date'] = ($data['fecha_renovacion'] == '' || $data['fecha_renovacion'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_renovacion']));

                    $shortTermConservationMicro = $this->ShortTermConservationMicro->patchEntity($shortTermConservationMicro,$data);

                    if ($this->ShortTermConservationMicro->save($shortTermConservationMicro)) {

                        $list_module = explode('/', $this->request->params['_matchedRoute']);

                        $user_id    = $this->Auth->User('id');
                        $module     = $list_module[(count($list_module)-4)];
                        $action     = $list_module[(count($list_module)-2)].'/'.$list_module[(count($list_module)-1)];
                        $station_id = $shortTermConservationMicro->id;
                        $recurso_id = '3';

                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                         $this->Flash->success(__('La Conservación a Corto Plazo fue creado satisfactoriamente.'));

                        return $this->redirect(['action' => 'index',$shortTermConservationMicro->bank_micro_id]);
                    }
                    $this->Flash->error(__('Hubo inconvenientes al crear la Conservación a Corto Plazo. Por favor, Otra vez intente.'));

             } catch (\Exception $e) {

                    $this->Flash->error(__('Hubo inconvenientes al crear la Conservación a Corto Plazo. Por favor, Otra vez intente.'));

                   return $this->redirect(['action' => 'index',$shortTermConservationMicro->bank_micro_id]);
            }
        }

        $lista_conservacion= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 520, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $lista_material= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 525, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $lista_lugar_almacenamiento= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 558, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

        $this->set(compact('scripts','shortTermConservationMicro','modulo','id','lista_conservacion','lista_material','lista_lugar_almacenamiento'));
        $this->set('_serialize', ['shortTermConservationMicro']);

        }else {

                 $this->Flash->error(__('Operación denegada.'));
                 return $this->redirect(['action' => 'index','controller'=>'BankMicro']);
        }
    }

    /**
     * Edit method
     *
     * @param string|null $id Short Term Conservation Micro id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null,$child=null)
    {
        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count!=NULL /*&& $validar*/ ){

            $shortTermConservationMicro = $this->ShortTermConservationMicro->find()
                                         ->where(['ShortTermConservationMicro.status !=' => '0','ShortTermConservationMicro.id'=>$child,'ShortTermConservationMicro.bank_micro_id'=>$id
                                            ])->first();

            if($shortTermConservationMicro==NULL){

                        $this->Flash->error(__('Operación denegada.'));
                        return $this->redirect(['action' => 'index',$id]);
            } else {

                    $modulo=$this->mod_padre ;
                    $scripts = ['assets/packages/jqueryvalidation/dist/jquery.validate'];
                    if ($this->request->is(['patch', 'post', 'put'])) {

                            $data=$this->request->getData();
                            $data['constime'] = ($data['fecha_conservacion'] == '' || $data['fecha_conservacion'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_conservacion']));
                             $data['renewal_date'] = ($data['fecha_renovacion'] == '' || $data['fecha_renovacion'] == NULL) ? NULL : date('Y-m-d', strtotime($data['fecha_renovacion']));
                             try{
                                    $shortTermConservationMicro = $this->ShortTermConservationMicro->patchEntity($shortTermConservationMicro,$data);

                                    if ($this->ShortTermConservationMicro->save($shortTermConservationMicro)) {

                                        $list_module = explode('/', $this->request->params['_matchedRoute']);

                                        $user_id    = $this->Auth->User('id');
                                        $module     = $list_module[(count($list_module)-5)];
                                        $action     = $list_module[(count($list_module)-3)].'/'.$list_module[(count($list_module)-2)];
                                        $station_id = $shortTermConservationMicro->id;
                                        $recurso_id = '3';

                                        $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                                        $this->Flash->success(__('La Conservación a Corto Plazo fue actualizada satisfactoriamente.'));

                                        return $this->redirect(['action' => 'index',$shortTermConservationMicro->bank_micro_id]);
                                    }
                                    $this->Flash->error(__('Hubo inconvenientes al actualizar la Conservación a Corto Plazo. Por favor, Otra vez intente.'));

                                } catch (\Exception $e) {

                                    $this->Flash->error(__('Hubo inconvenientes al actualizar la Conservación a Corto Plazo. Por favor, Otra vez intente.'));
                                    return $this->redirect(['action' => 'index']);
                            }
                    }

                    $lista_conservacion= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 520, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

                    $lista_material= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 525, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

                    $lista_lugar_almacenamiento= $this->OptionList->find('list', ['keyField' => 'id', 'valueField' => 'name'])->where(['parent_id' => 558, 'status' => 1, 'OR' => [['resource_id' => 3]] ]);

                    $shortTermConservationMicro->constime=($shortTermConservationMicro->constime == NULL) ? NULL : date('d-m-Y', strtotime($shortTermConservationMicro->constime));
                    $shortTermConservationMicro->renewal_date=($shortTermConservationMicro->renewal_date == NULL) ? NULL : date('d-m-Y', strtotime($shortTermConservationMicro->renewal_date));

                    $this->set(compact('scripts','shortTermConservationMicro','modulo','lista_estado','id','lista_conservacion','lista_material','lista_lugar_almacenamiento','child'));
                    $this->set('_serialize', ['shortTermConservationMicro']);

            }

         }

        else {
                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller' => 'BankMicro']);
        }


    }

    /**
     * Delete method
     *
     * @param string|null $id Short Term Conservation Micro id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null,$child=null)
    {
        $bankMicro_count = $this->BankMicro->find()->where(['BankMicro.status '=>'1','BankMicro.id'=>$id])->first();
        $passport = $this->Passport->find()->where(['id '=>$bankMicro_count->passport_id])->first();
        $validar=$this->permiso['role_id']==1?true:$this->permiso['station_id']==$passport['station_current_id'];

        if($bankMicro_count!=NULL /*&& $validar*/){

            $this->request->is(['post', 'delete']);

            $shortTermConservationMicro = $this->ShortTermConservationMicro->find()
                                         ->where(['ShortTermConservationMicro.status !=' => '0','ShortTermConservationMicro.id'=>$child,'ShortTermConservationMicro.bank_micro_id'=>$id
                                            ])->first();

            if($shortTermConservationMicro==NULL){

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index',$id]);
            }else{

                $shortTermConservationMicro['status'] = 0;

                if ($this->ShortTermConservationMicro->save($shortTermConservationMicro)) {

                    $list_module = explode('/', $this->request->params['_matchedRoute']);

                    $user_id    = $this->Auth->User('id');
                    $module     = $list_module[(count($list_module)-5)];
                    $action     = $list_module[(count($list_module)-3)].'/'.$list_module[(count($list_module)-2)];
                    $station_id = $shortTermConservationMicro->id;
                    $recurso_id = '3';

                    $this->Functions->saveLogWeb($module, $station_id, $action, $user_id, $recurso_id);

                    $this->Flash->success(__('La Conservación a Corto Plazo del Material fue eliminado satisfactoriamente.'));
                } else {
                     $this->Flash->error(__('Hubo inconvenientes al eliminar la Conservación a Corto Plazo del Material . Por favor, Otra vez intente.'));
                }

               return $this->redirect(['action' => 'index', $shortTermConservationMicro->bank_micro_id]);
            }

        }else{

                $this->Flash->error(__('Operación denegada.'));
                return $this->redirect(['action' => 'index','controller' => 'BankMicro']);

        }
    }

    public function exportartabla($id = null) {

        if ($this->request->is('post')) {

            $data = $this->request->getData();

            $filePath = WWW_ROOT .'reportes/'.$data['filename'].'.xlsx';

            if(file_exists($filePath)){

                $this->response->file($filePath , array('download'=> true));

                return $this->response;

            } else {

                $this->Flash->error(__('No existe el archivo.'));
                return $this->redirect(['action' => 'index']);
            }
        }
    }


}
